// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFweFCBQQQf_RHhbYMBMI57HZRqRLcvW0',
    appId: '1:367245762922:web:b21e6e2d7c79df4c778513',
    messagingSenderId: '367245762922',
    projectId: 'fruitsapp-61a6b',
    authDomain: 'fruitsapp-61a6b.firebaseapp.com',
    storageBucket: 'fruitsapp-61a6b.firebasestorage.app',
    measurementId: 'G-S284BRLMS6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACugSDr4op1cG0GsbnLro8Lz9k-hlPG7Q',
    appId: '1:367245762922:android:35484bfad7e7ff2c778513',
    messagingSenderId: '367245762922',
    projectId: 'fruitsapp-61a6b',
    storageBucket: 'fruitsapp-61a6b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDV5wHsxv1lxx-mlNpaXxQUj9HZ7yUpsBI',
    appId: '1:367245762922:ios:3fbf4aecbfdaba2e778513',
    messagingSenderId: '367245762922',
    projectId: 'fruitsapp-61a6b',
    storageBucket: 'fruitsapp-61a6b.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDV5wHsxv1lxx-mlNpaXxQUj9HZ7yUpsBI',
    appId: '1:367245762922:ios:3fbf4aecbfdaba2e778513',
    messagingSenderId: '367245762922',
    projectId: 'fruitsapp-61a6b',
    storageBucket: 'fruitsapp-61a6b.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFweFCBQQQf_RHhbYMBMI57HZRqRLcvW0',
    appId: '1:367245762922:web:2a01c3e1b41ea8f9778513',
    messagingSenderId: '367245762922',
    projectId: 'fruitsapp-61a6b',
    authDomain: 'fruitsapp-61a6b.firebaseapp.com',
    storageBucket: 'fruitsapp-61a6b.firebasestorage.app',
    measurementId: 'G-ZYXZ4T6TH6',
  );

}