// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDL0Z233xYI_su-79PsXW8ajsv8FFBX2I',
    appId: '1:559124201673:web:4d949fa3ca1f7417eb4d18',
    messagingSenderId: '559124201673',
    projectId: 'ecommerce-f5be2',
    authDomain: 'ecommerce-f5be2.firebaseapp.com',
    storageBucket: 'ecommerce-f5be2.firebasestorage.app',
    measurementId: 'G-N9K7EEBXT3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5bDOmjaM5tqEECJ-7wOaQ3ge2Y37Y2gg',
    appId: '1:559124201673:android:1125511dad802656eb4d18',
    messagingSenderId: '559124201673',
    projectId: 'ecommerce-f5be2',
    storageBucket: 'ecommerce-f5be2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSYqIPlNKeanAT4gORrV6K_28RThrPzxQ',
    appId: '1:559124201673:ios:6056f13f90061e5deb4d18',
    messagingSenderId: '559124201673',
    projectId: 'ecommerce-f5be2',
    storageBucket: 'ecommerce-f5be2.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSYqIPlNKeanAT4gORrV6K_28RThrPzxQ',
    appId: '1:559124201673:ios:6056f13f90061e5deb4d18',
    messagingSenderId: '559124201673',
    projectId: 'ecommerce-f5be2',
    storageBucket: 'ecommerce-f5be2.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDL0Z233xYI_su-79PsXW8ajsv8FFBX2I',
    appId: '1:559124201673:web:6f40b750f8c91bb7eb4d18',
    messagingSenderId: '559124201673',
    projectId: 'ecommerce-f5be2',
    authDomain: 'ecommerce-f5be2.firebaseapp.com',
    storageBucket: 'ecommerce-f5be2.firebasestorage.app',
    measurementId: 'G-0NWVEPS2LX',
  );

}